import HautevilleHouse.CategoricityCompletenessCanonicalLaneLean.ModelTheoryStructures
import HautevilleHouse.CategoricityCompletenessCanonicalLaneLean.CompleteTypeBridge
import HautevilleHouse.CategoricityCompletenessCanonicalLaneLean.ElementarClassDef
import HautevilleHouse.CategoricityCompletenessCanonicalLaneLean.CategoricityLSP
import HautevilleHouse.CategoricityCompletenessCanonicalLaneLean.CategoricityCompletenessEndgame

namespace HautevilleHouse
namespace CategoricityCompletenessCanonicalLaneLean

def packageName : String := "CategoricityCompletenessCanonicalLaneLean"

end CategoricityCompletenessCanonicalLaneLean
end HautevilleHouse